Repository cs4218/cs4218-project-2024-team06, pull requests merged in 2024-09, with the labels that each got.

#2 Add .env file into gitignore
  .env
  .gitignore
  package-lock.json
  package.json
Labels: setup

#8 Add test to ensure policy page can be rendered
  client/src/pages/Policy.test.js
Labels: medium-priority, unit-testing

#7 Add test for contact page
  client/src/pages/Contact.test.js
Labels: medium-priority, unit-testing

#9 Add test for footer and categoryController
  client/src/components/footer.test.js
  controllers/categoryController.test.js
  jest.setup.js
  package-lock.json
  package.json
Labels: medium-priority, unit-testing

#4 Unit Tests for Auth (Sprint 1)
  babel.config.cjs
  client/src/components/AdminMenu.test.js
  client/src/context/auth.test.js
  client/src/pages/admin/AdminDashboard.test.js
  controllers/authControllerForgotPasswordController.test.js
  controllers/authControllerLoginController.test.js
  controllers/authControllerRegisterController.test.js
  controllers/authControllerTestController.test.js
  helpers/authHelper.test.js
  middlewares/authMiddleware.test.js
  package-lock.json
  package.json
Labels: high-priority, unit-testing

#6 Add node js workflow
  .github/workflows/node.js.yml
Labels: setup, medium-priority

#21 Unit test general
  client/src/components/Header.test.js
  client/src/components/Layout.test.js
  client/src/components/Spinner.test.js
  client/src/pages/About.test.js
  client/src/pages/Pagenotfound.test.js
  config/db.test.js
Labels: medium-priority, unit-testing

#22 Unit test category
  client/src/hooks/useCategory.test.js
  client/src/pages/Categories.test.js
  models/categoryModel.test.js
  package-lock.json
  package.json
Labels: medium-priority, unit-testing

#23 Add Unit Tests for Register and Login Client Components
  client/src/_site/pages/Auth/Login.test.js
  client/src/_site/pages/Auth/Register.test.js
  client/src/pages/Auth/Login.test.js
  client/src/pages/Auth/Register.test.js
  controllers/authControllerLoginController.test.js
Labels: high-priority, unit-testing
