Repository cs4218/cs4218-project-2024-team06, pull requests merged in 2024-10, with the labels that each got.

#25 Unit test payment
  controllers/productController.test.js
Labels: medium-priority, unit-testing

#29 Tidy Up Auth Test Cases
  client/src/components/AdminMenu.test.js
  client/src/context/auth.test.js
  client/src/pages/Auth/Login.test.js
  client/src/pages/Auth/Register.test.js
  client/src/pages/admin/AdminDashboard.test.js
  controllers/authControllerForgotPasswordController.test.js
  controllers/authControllerLoginController.test.js
  controllers/authControllerRegisterController.test.js
  controllers/authControllerTestController.test.js
  helpers/authHelper.test.js
  middlewares/authMiddleware.test.js
Labels: enhancement, high-priority, unit-testing

#26 Unit test cart
  client/src/context/cart.test.js
  client/src/pages/CartPage.test.js
Labels: medium-priority, unit-testing

#27 Unit test home
  client/src/pages/HomePage.test.js
Labels: medium-priority, unit-testing

#28 Reduce test case
  client/src/components/Header.test.js
  client/src/components/Layout.test.js
  client/src/components/Spinner.test.js
  client/src/components/footer.test.js
  client/src/hooks/useCategory.test.js
  client/src/pages/About.test.js
  client/src/pages/Categories.test.js
  client/src/pages/Pagenotfound.test.js
  config/db.test.js
  controllers/categoryController.test.js
  controllers/productController.test.js
  models/categoryModel.test.js
Labels: medium-priority, unit-testing

#30 Add README and update CI workflow
  .github/workflows/node.js.yml
  README.md
Labels: enhancement

#32 Finalise 25 test case for sprint 2
  client/package-lock.json
  client/package.json
  client/src/components/Form/SearchInput.test.js
  client/src/context/search.test.js
  client/src/pages/CategoryProduct.test.js
  client/src/pages/ProductDetails.test.js
  client/src/pages/Search.test.js
  controllers/productController.test.js
Labels: high-priority, unit-testing

#10 Unit test user management
  babel.config.cjs
  client/src/components/Routes/Private.test.js
  client/src/components/UserMenu.test.js
  client/src/pages/user/Dashboard.test.js
  client/src/pages/user/Orders.test.js
  client/src/pages/user/Profile.test.js
  controllers/authControllerGetAllOrdersController.test.js
  controllers/authControllerGetOrdersController.test.js
  controllers/authControllerOrderStatusController.test.js
  controllers/authControllerUpdateProfileController.test.js
  models/orderModel.test.js
  models/userModel.test.js
  package-lock.json
Labels: medium-priority, unit-testing

#44 Integration test zenith
  client/src/pages/categoriesIntegration.test.js
  controllers/categoryControllerIntegration.test.js
  controllers/productControllerIntegration.test.js
Labels: high-priority, integration-testing

#45 UI Tests
  data/images/blouses/checkered-blue-blouses.webp
  data/images/blouses/dotted-blue-blouse.webp
  data/images/blouses/striped-blue-blouse.jpg
  data/images/shirts/checkered-blue-shirt.webp
  data/images/shirts/dotted-blue-shirt.jpg
  data/images/shirts/striped-blue-shirt.jpg
  data/index.js
  global-playwright-setup.js
  package-lock.json
  package.json
  playwright-report/index.html
  playwright.config.cjs
  tests/adminCreateCategory.spec.mjs
  tests/searchProductBySearchBar.spec.mjs
  tests/updateProfile.spec.mjs
Labels: medium-priority, ui-testing

#43 Create Auth-related Integration Tests
  client/src/pages/Auth/LoginIntegration.test.js
  client/src/pages/Auth/RegisterIntegration.test.js
  client/src/pages/admin/AdminDashboardIntegration.test.js
  controllers/forgotPasswordControllerIntegration.test.js
  helpers/authHelperIntegration.test.js
  middlewares/authMiddlewareIntegration.test.js
Labels: high-priority, integration-testing

#50 UI test kangquan
  playwright.config.cjs
  tests/authenticatedAddingAndRemoving.spec.cjs
  tests/register.spec.cjs
  tests/unauthenticatedCheckout.spec.cjs
Labels: ui-testing

#52 Add integration test to codebase
  controllers/getProductControllerIntegration.test.js
  controllers/productCountControllerIntegration.test.js
  controllers/productFiltersControllerIntegration.test.js
  controllers/productPhotoControllerIntegration.test.js
Labels: integration-testing

#37 Set up Code Coverage via SonarQube
  README.md
  client/src/pages/CategoryProduct.test.js
  client/src/pages/ProductDetails.test.js
  controllers/categoryController.test.js
  middlewares/authMiddlewareIntegration.test.js
  package.json
  sonar-project.properties
  tests-examples/demo-todo-app.spec.js
  tests/example.spec.cjs
  tests/searchProductBySearchBar.spec.mjs
  tests/trial.spec.cjs
  tests/updateProfile.spec.mjs
  tests/user.spec.cjs
Labels: setup, medium-priority
